<div class='container' style="font-size:10pt">
    <div class='row justify-content-center align-items-center h-75 
    
    '>
        <div class='col-md-6 justify-content-center'>
            <form action="\" method="Post" class='p-4 border' style="color:rgba(29,161,242,1.00);">

                <div class='text-center'>
                    <i id='icone' class="fab fa-twitter fa-3x mb-3"></i>
                </div>

                <h3 class='mb-4 text-center'>Conta criada com sucesso</h3>

                <p class='text-dark'>
                    Sua conta foi criada com sucesso, você pode acessar agora e começar a utilizar nossos serviços.
                </p>

                <input type="submit" class='btn btn-primary w-100' value="logar agora">
            </form>
        </div>
    </div>
</div>