
<div class="col-md-6 ">
    <div class='row' class='w-100'>
        <form action="/twittar" method="POST" class='col-12 p-4' style="background-color: #E8F5FD;">
            <div class='form-group'> 
                <textarea name="conteudo" id="textarea" rows="3" class='form-control w-100'></textarea>
            </div>

            <div class='text-right px-3'>
                <input type="submit" class='btn btn-primary' value="tweet">
            </div>
        </form>
    </div>
    <div class='row'>
        <?php foreach($this->viewObj->twitts as $key => $twitt){?>
            <article class='col-12 p-4 mb-5 twitt'>
                <div>
                    <h5 class='d-inline'><?= $twitt['nome_usuario'] ?></h5>
                    <small class='text-muted'>- <?= $twitt['date_twitt'] ?>-</small>
                </div>
                <div class='my-3'>
                    <?= $twitt['conteudo_twitt'] ?>
                </div>
                <div class='text-right'>
                    <?php if($_SESSION['id'] == $twitt['id_usuario']){?>
                        <a href="/remover?id_twitt=<?= $twitt['id_twitt'] ?>" class='btn btn-danger text-white'>remover</a>
                    <?php }?>
                </div>
            </article>
        <?php } ?>
    </div>
</div>
<div class="col-md-3">
    <div class='border'>
        <div class='border-bottom p-2'>
            <h5>Quem seguir</h5>
        </div>
        <div class='p-2'>
            <a href="/seguir">prucure pessoas pra seguir</a>
        </div>
    </div>
</div>
